# Generated by Django 5.1 on 2024-08-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
