# Generated by Django 5.1 on 2024-08-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_student_stud_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
