# Generated by Django 5.1 on 2024-08-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_remove_student_stud_photo_student_stud_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_profile_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_image',
            field=models.ImageField(default=None, upload_to='stud_profile'),
        ),
    ]
